version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/dockerfile/aws-mkt-lm"
      - "/dockerfile/aws-mkt-pro"
      - "/dockerfile/compat"
      - "/dockerfile/kpow-ce"
      - "/dockerfile/kpow"
      - "/dockerfile/rh-ubi"
      - "/dockerfile/temurin-ubi"
      - "/dockerfile/kpow-amazoncorretto25"
    ignore:
      - dependency-name: "amazoncorretto"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
